services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: eastern-religion-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./.env:/app/.env:ro
      - ./backend:/app/backend
    networks:
      - eastern-religion-network-dev
    restart: unless-stopped
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eastern-religion-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - eastern-religion-network-dev
    restart: unless-stopped
    command: ["npm", "run", "dev"]

networks:
  eastern-religion-network-dev:
    driver: bridge