services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: eastern-religion-backend
    environment:
      - PORT=8000
    volumes:
      - ./.env:/app/.env:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend-easternchatbot.nguyenvanloc.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - localnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eastern-religion-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`eastern-chatbot.nguyenvanloc.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - localnet
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  localnet:
    external: true
    name: localnet