services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: buddhism-religion-backend
    environment:
      - PORT=8000
    volumes:
      - ./.env:/app/.env:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.buddhism-backend.rule=Host(`backend-buddhismchatbot.nguyenvanloc.com`) | Host(`backend-sanghagpt.nguyenvanloc.com`)"
      - "traefik.http.routers.buddhism-backend.entrypoints=websecure"
      - "traefik.http.routers.buddhism-backend.tls=true"
      - "traefik.http.services.buddhism-backend.loadbalancer.server.port=8000"
    networks:
      - localnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: buddhism-religion-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://backend-sanghagpt.nguyenvanloc.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.buddhism-frontend.rule=Host(`buddhism-chatbot.nguyenvanloc.com`) | Host(`sanghagpt.nguyenvanloc.com`)"
      - "traefik.http.routers.buddhism-frontend.entrypoints=websecure"
      - "traefik.http.routers.buddhism-frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - localnet
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  localnet:
    external: true
